[workspace]
resolver = "2"
members  = ["crates/*", "apps/*"]

[workspace.package]
description  = "Ultra-fast typescript compiler"
authors      = ["Don Isaac <don@donisaac.dev>"]
edition      = "2021"
license      = "MIT"
rust-version = "1.76.0"                         # Support last 6 minor versions

[workspace.lints.clippy]
all        = { level = "warn", priority = -1 }
empty_docs = { level = "allow", priority = 1 }

dbg_macro    = "warn"
print_stdout = "warn"
print_stderr = "warn"

module_name_repititions = "allow"
too_many_lines          = "allow"
must_use_candidate      = "allow"
doc_markdown            = "allow"
missing_const_for_fn    = "allow"

[workspace.dependencies]
oxbuild_compiler = { path = "crates/oxbuild_compiler" }

oxc = { version = "0.29.0" }
